# Generated by Django 2.1.7 on 2019-05-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190502_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish']},
        ),
    ]
