# Generated by Django 2.1.7 on 2019-05-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
